"""Add comms and infra form

Revision ID: 57c550aece0d
Revises: 1c47c6cef1b4
Create Date: 2024-05-18 14:17:16.839260

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '57c550aece0d'
down_revision = '1c47c6cef1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communications_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('commsInfrastructure', sa.String(length=50), nullable=True),
    sa.Column('commsPhoneAndInternet', sa.String(length=50), nullable=True),
    sa.Column('commsAvailability', sa.String(length=50), nullable=True),
    sa.Column('commsAlternative', sa.String(length=50), nullable=True),
    sa.Column('commsComments', sa.String(length=250), nullable=True),
    sa.Column('connectElectricity', sa.String(length=50), nullable=True),
    sa.Column('connectFuelAvailability', sa.String(length=50), nullable=True),
    sa.Column('connectBackupPower', sa.String(length=50), nullable=True),
    sa.Column('connectLocalControl', sa.String(length=250), nullable=True),
    sa.Column('connectComments', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_communications_form_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('roadCondition', sa.String(length=50), nullable=True),
    sa.Column('roadDamage', sa.String(length=50), nullable=True),
    sa.Column('roadAccess', sa.String(length=50), nullable=True),
    sa.Column('roadComments', sa.String(length=250), nullable=True),
    sa.Column('buildingIntegrity', sa.String(length=50), nullable=True),
    sa.Column('buildingType', sa.String(length=50), nullable=True),
    sa.Column('buildingDamage', sa.String(length=50), nullable=True),
    sa.Column('buildingComments', sa.String(length=250), nullable=True),
    sa.Column('utilityPower', sa.String(length=50), nullable=True),
    sa.Column('utilityWater', sa.String(length=50), nullable=True),
    sa.Column('utilityComms', sa.String(length=50), nullable=True),
    sa.Column('utilityComments', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_infrastructure_form_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_form', schema=None) as batch_op:
        batch_op.alter_column('securityRiskComments',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('incidentsComments',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_form', schema=None) as batch_op:
        batch_op.alter_column('incidentsComments',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('securityRiskComments',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    op.drop_table('infrastructure_form')
    op.drop_table('communications_form')
    # ### end Alembic commands ###
