"""Update users, add organisations, securityForm

Revision ID: 8157c639c74d
Revises: 34039bfbf162
Create Date: 2024-04-17 07:32:48.325310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8157c639c74d'
down_revision = '34039bfbf162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('security_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('armedGroupsPresence', sa.String(length=50), nullable=True),
    sa.Column('reportOfViolence', sa.String(length=50), nullable=True),
    sa.Column('localEnforcementPresence', sa.String(length=50), nullable=True),
    sa.Column('securityRiskComments', sa.String(length=500), nullable=True),
    sa.Column('incidentsReported', sa.String(length=50), nullable=True),
    sa.Column('riskToRelief', sa.String(length=50), nullable=True),
    sa.Column('incidentsComments', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_security_form_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('organisation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'organisations', ['organisation_id'], ['id'])
        batch_op.drop_column('created_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organisation_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('hashed_password')

    op.drop_table('security_form')
    op.drop_table('organisations')
    # ### end Alembic commands ###
